blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogDetailView, BlogListView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('list/', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, **NULLABLE, verbose_name='Slug')
    body = models.TextField(max_length=100, verbose_name='Содержимое')
    image = models.ImageField(upload_to='blog/', verbose_name='Изображение', **NULLABLE)
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True, **NULLABLE)
    is_published = models.BooleanField(default=True, verbose_name='Активно')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

blog/views.py
from django.shortcuts import render
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.models import Blog


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Блоги'
        return context


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title
        return context


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'is_published', 'image')
    success_url = reverse_lazy('blog:create')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание блога'
        return context


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body', 'is_published', 'image')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        from django.urls import reverse
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base_product.html' %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Хотите удалить статью: "{{ object.title | truncatechars:40 }}"? </p>
                        <button Type="submit" class="btn btn-success"> Подтвердить </button>
                        <button Type="submit" href="{% url 'blog:list' %}" class="btn btn-success"> Вернуться назад </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base_product.html' %}

{% load image_tag %}
{% block title %} Блог {% endblock %}

{% block content %}
<h1 align="center"> {{ object|title }} ( {{ object.slug }} ) </h1>

<div class="card px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center" style="width: 24rem;">
    <div class="card-body">
        <img src="{% mymedia object.image %}" width="100" height="111">
        <p class="card-text">Содержимое: {{ object.body }}</p>
        <p class="card-text">Дата создания: {{ object.created_at }}</p>
        <p class="card-text"> Просмотров: {{ object.views_count }}</p>
        <div class="d-grid gap-2 mx-auto">
            <a href="{% url 'blog:list' %}" class="w-100 btn btn-lg btn-outline-warning"> Назад </a>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base_product.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Добавить блог</h1>
</div>

<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Редактирование блога</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="mb-3">
                        <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Сохранить</button>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'blog:list' %}" class="w-100 btn btn-lg btn-outline-primary">Обратно</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base_product.html' %}

{% load image_tag %}

{% block title %} Блог {% endblock %}

{% block content %}

<a class="btn btn-outline-success" href="{% url 'blog:create' %}"> Добавить статью </a>

{% for object in object_list %}
<div class="col">
    <div class="card shadow-sm">
        <div class="card-body">
            <h4><p class="card-text">{{ object.title }} </p></h4>
            <img src="{% mymedia object.image %}" width="150" height="111">
            <p class="card-text">Содержимое: {{ object.body }} </p>
            <p class="card-text">Дата создания: {{ object.created_at }} </p>
            <a href="{% url 'blog:view' object.pk %}">Подробнее</a>
            <a href="{% url 'blog:edit' object.pk %}" class="w-100 btn btn-lg btn-outline-success"> Редактировать</a>
            <a href="{% url 'blog:delete' object.pk %}" class="w-100 btn btn-lg btn-outline-success"> Удалить</a>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}